require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes
